<a href="https://colab.research.google.com/github/BishalDas1010/BIT_project_TInyML/blob/main/BIT_test_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To connect to your Google Drive, you can use the following code. This will prompt you to authorize Colab to access your Drive.

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

File Extract

In [6]:
import zipfile

zip_file = "/content/drive/MyDrive/Dataset_For_Bit/human+activity+recognition+using+smartphones (1).zip"  # Your ZIP file

with zipfile.ZipFile(zip_file, "r") as zip_ref:
    zip_ref.extractall("extracted_files")

print("ZIP extracted successfully!")

ZIP extracted successfully!

In [7]:
location = "/content/extracted_files/UCI HAR Dataset.zip"
with zipfile.ZipFile(location, "r") as zip_ref:
    zip_ref.extractall("extracted_files")

print("ZIP extracted successfully!")

ZIP extracted successfully!

data input as TXT

In [11]:
import pandas as pd
dataset = "/content/extracted_files/UCI HAR Dataset/test/Inertial Signals/body_acc_x_test.txt"
df =pd.read_csv(dataset,sep="\t")
df.head(10)

  1.1653150e-002  1.3109090e-002  1.1268850e-002  2.7830730e-002  2.3183500e-003 -1.8965500e-002 -6.1920230e-002 -9.4248130e-002 -7.9534200e-002 -7.0083760e-002 -1.9152480e-002 -2.2668950e-003 -3.0111470e-002 -1.1910260e-002 -1.5542110e-002 -1.6666170e-002 -6.6302790e-003 -2.3480930e-002 -1.7627590e-002 -2.1150170e-002 -3.2659070e-002 -2.2478410e-002 -1.0196890e-002 -3.1196910e-003 -1.6495820e-002 -2.0441880e-002 -2.7567620e-002 -5.5032500e-002 -5.7479710e-002 -4.7095990e-002 -2.8361690e-002 -1.7184890e-002 -7.3758860e-003  2.4778770e-002  2.3929340e-002  2.1248370e-002  9.6999630e-003 -3.5118900e-002 -1.0733260e-002  2.3672330e-002  1.4929500e-002  2.1906200e-002  5.0844080e-003 -1.3070070e-002 -7.9809120e-003 -1.2763990e-002 -9.8686730e-003 -3.6970220e-003  4.7806470e-003  7.9291720e-003 -5.4944340e-004 -9.1546860e-004 -4.9868180e-003  9.0750290e-003  3.3040610e-002  1.9763320e-002  1.0038920e-005 -1.7139270e-002 -2.9957720e-002 -9.4479730e-003  5.1335230e-003 -2.5121430e-003  3.2194320e-003  1.2330130e-002  9.2796290e-003  4.9297110e-003  3.9535960e-003  9.2144290e-003  1.6156130e-002  1.4079400e-002  1.3105210e-002  2.1246960e-002  2.6823440e-002  3.1054370e-002  3.7886060e-002  2.6462870e-002 -2.1441150e-002 -6.0567950e-002 -2.4725380e-002  2.0272130e-002 -1.9340940e-003 -8.9067130e-003  9.5376650e-003 -4.3316630e-003 -1.8638360e-003  4.9550750e-003 -5.3361360e-003  2.0007890e-003 -1.7075180e-003 -6.4634980e-003  2.0412210e-004 -3.6400110e-003  8.2683690e-005 -1.4416150e-003 -5.9593910e-003  3.4398910e-004  5.5799520e-004  2.3814270e-003  1.8277850e-003 -1.4560660e-003 -2.0005970e-004 -5.7041380e-004  2.6049420e-003  2.6436190e-003  1.5970290e-003  3.8177820e-003  1.6479750e-003  2.9432210e-003  5.5816380e-003  6.2567030e-003  5.1689760e-003 -2.5212320e-003 -6.3626070e-003 -2.4966130e-003  2.4552680e-003  4.4235590e-003  2.1102270e-003 -5.5878910e-004 -2.9442470e-003 -1.2468990e-003  2.8482550e-003  2.3545580e-003  2.7209850e-003  3.2552900e-003  1.3010800e-003  1.2915110e-003  1.4699970e-003  2.5738410e-003
0    9.2796290e-003  4.9297110e-003  3.9535960e-0...
1    5.7319450e-003  7.0656500e-003  5.1097580e-0...
2    4.5194670e-004  6.0393820e-004 -2.4845620e-0...
3   -4.3623790e-003 -2.7653920e-003 -4.9047840e-0...
4   -1.0956640e-003 -3.2297430e-003 -3.4296850e-0...
5   -4.1915910e-004 -1.6501930e-003 -1.5937580e-0...
6   -8.8643840e-004 -2.6454220e-003 -1.6073520e-0...
7   -3.0859370e-003 -2.9502560e-003 -3.0557420e-0...
8   -3.4367520e-004  2.2914090e-003  1.7869940e-0...
9    2.1013520e-003  3.8859030e-003  1.3827780e-0...

In [14]:
import os

path = "/content/extracted_files/UCI HAR Dataset"

for root, dirs, files in os.walk(path):
    for file in files:
        print(os.path.join(root, file))

/content/extracted_files/UCI HAR Dataset/.DS_Store
/content/extracted_files/UCI HAR Dataset/README.txt
/content/extracted_files/UCI HAR Dataset/activity_labels.txt
/content/extracted_files/UCI HAR Dataset/features_info.txt
/content/extracted_files/UCI HAR Dataset/features.txt
/content/extracted_files/UCI HAR Dataset/train/subject_train.txt
/content/extracted_files/UCI HAR Dataset/train/X_train.txt
/content/extracted_files/UCI HAR Dataset/train/y_train.txt
/content/extracted_files/UCI HAR Dataset/train/Inertial Signals/body_acc_z_train.txt
/content/extracted_files/UCI HAR Dataset/train/Inertial Signals/body_acc_x_train.txt
/content/extracted_files/UCI HAR Dataset/train/Inertial Signals/body_gyro_y_train.txt
/content/extracted_files/UCI HAR Dataset/train/Inertial Signals/body_gyro_x_train.txt
/content/extracted_files/UCI HAR Dataset/train/Inertial Signals/body_acc_y_train.txt
/content/extracted_files/UCI HAR Dataset/train/Inertial Signals/body_gyro_z_train.txt
/content/extracted_files/UCI HAR Dataset/train/Inertial Signals/total_acc_z_train.txt
/content/extracted_files/UCI HAR Dataset/train/Inertial Signals/total_acc_x_train.txt
/content/extracted_files/UCI HAR Dataset/train/Inertial Signals/total_acc_y_train.txt
/content/extracted_files/UCI HAR Dataset/test/subject_test.txt
/content/extracted_files/UCI HAR Dataset/test/y_test.txt
/content/extracted_files/UCI HAR Dataset/test/X_test.txt
/content/extracted_files/UCI HAR Dataset/test/Inertial Signals/body_acc_y_test.txt
/content/extracted_files/UCI HAR Dataset/test/Inertial Signals/body_gyro_z_test.txt
/content/extracted_files/UCI HAR Dataset/test/Inertial Signals/total_acc_x_test.txt
/content/extracted_files/UCI HAR Dataset/test/Inertial Signals/body_gyro_y_test.txt
/content/extracted_files/UCI HAR Dataset/test/Inertial Signals/total_acc_z_test.txt
/content/extracted_files/UCI HAR Dataset/test/Inertial Signals/total_acc_y_test.txt
/content/extracted_files/UCI HAR Dataset/test/Inertial Signals/body_gyro_x_test.txt
/content/extracted_files/UCI HAR Dataset/test/Inertial Signals/body_acc_z_test.txt
/content/extracted_files/UCI HAR Dataset/test/Inertial Signals/body_acc_x_test.txt

In [19]:
#for total data set
import pandas as pd

X_train = pd.read_csv(
    "/content/extracted_files/UCI HAR Dataset/train/X_train.txt",
    sep=r'\s+',
    header=None
)

print("The shape of thedataset",X_train.shape)
print("Train head ",X_train.head())

The shape of thedataset (7352, 561)
Train head          0         1         2         3         4         5         6    \
0  0.288585 -0.020294 -0.132905 -0.995279 -0.983111 -0.913526 -0.995112
1  0.278419 -0.016411 -0.123520 -0.998245 -0.975300 -0.960322 -0.998807
2  0.279653 -0.019467 -0.113462 -0.995380 -0.967187 -0.978944 -0.996520
3  0.279174 -0.026201 -0.123283 -0.996091 -0.983403 -0.990675 -0.997099
4  0.276629 -0.016570 -0.115362 -0.998139 -0.980817 -0.990482 -0.998321

        7         8         9    ...       551       552       553       554  \
0 -0.983185 -0.923527 -0.934724  ... -0.074323 -0.298676 -0.710304 -0.112754
1 -0.974914 -0.957686 -0.943068  ...  0.158075 -0.595051 -0.861499  0.053477
2 -0.963668 -0.977469 -0.938692  ...  0.414503 -0.390748 -0.760104 -0.118559
3 -0.982750 -0.989302 -0.938692  ...  0.404573 -0.117290 -0.482845 -0.036788
4 -0.979672 -0.990441 -0.942469  ...  0.087753 -0.351471 -0.699205  0.123320

        555       556       557       558       559       560
0  0.030400 -0.464761 -0.018446 -0.841247  0.179941 -0.058627
1 -0.007435 -0.732626  0.703511 -0.844788  0.180289 -0.054317
2  0.177899  0.100699  0.808529 -0.848933  0.180637 -0.049118
3 -0.012892  0.640011 -0.485366 -0.848649  0.181935 -0.047663
4  0.122542  0.693578 -0.615971 -0.847865  0.185151 -0.043892

[5 rows x 561 columns]

In [23]:
#for total data set
import pandas as pd

X_train = pd.read_csv(
    "/content/extracted_files/UCI HAR Dataset/test/X_test.txt",
    sep=r'\s+',
    header=None
)

print("The shape of thedataset",X_train.shape)
print("Train head ",X_train.head())

The shape of thedataset (2947, 561)
Train head          0         1         2         3         4         5         6    \
0  0.257178 -0.023285 -0.014654 -0.938404 -0.920091 -0.667683 -0.952501
1  0.286027 -0.013163 -0.119083 -0.975415 -0.967458 -0.944958 -0.986799
2  0.275485 -0.026050 -0.118152 -0.993819 -0.969926 -0.962748 -0.994403
3  0.270298 -0.032614 -0.117520 -0.994743 -0.973268 -0.967091 -0.995274
4  0.274833 -0.027848 -0.129527 -0.993852 -0.967445 -0.978295 -0.994111

        7         8         9    ...       551       552       553       554  \
0 -0.925249 -0.674302 -0.894088  ...  0.071645 -0.330370 -0.705974  0.006462
1 -0.968401 -0.945823 -0.894088  ... -0.401189 -0.121845 -0.594944 -0.083495
2 -0.970735 -0.963483 -0.939260  ...  0.062891 -0.190422 -0.640736 -0.034956
3 -0.974471 -0.968897 -0.938610  ...  0.116695 -0.344418 -0.736124 -0.017067
4 -0.965953 -0.977346 -0.938610  ... -0.121711 -0.534685 -0.846595 -0.002223

        555       556       557       558       559       560
0  0.162920 -0.825886  0.271151 -0.720009  0.276801 -0.057978
1  0.017500 -0.434375  0.920593 -0.698091  0.281343 -0.083898
2  0.202302  0.064103  0.145068 -0.702771  0.280083 -0.079346
3  0.154438  0.340134  0.296407 -0.698954  0.284114 -0.077108
4 -0.040046  0.736715 -0.118545 -0.692245  0.290722 -0.073857

[5 rows x 561 columns]

In [26]:
y_train = pd.read_csv(
    "/content/extracted_files/UCI HAR Dataset/test/X_test.txt",
    header=None
)

print(y_train.head(1))

                                                   0
0    2.5717778e-001 -2.3285230e-002 -1.4653762e-0...

In [30]:
y_test = pd.read_csv(
    "/content/extracted_files/UCI HAR Dataset/test/y_test.txt",
    header=None
)
#unipue values
print(y_test[0].unique())

[5 4 6 1 3 2]

In [33]:
# Load activity labels
activity_labels = pd.read_csv(
    "/content/extracted_files/UCI HAR Dataset/activity_labels.txt",
    header=None,
    delim_whitespace=True
)

# Create mapping dictionary
label_map = dict(zip(activity_labels[0], activity_labels[1]))

# Apply mapping
y_test_named = y_test[0].map(label_map)
y_test_named.head()
print(y_test_named.unique())

['STANDING' 'SITTING' 'LAYING' 'WALKING' 'WALKING_DOWNSTAIRS'
 'WALKING_UPSTAIRS']

/tmp/ipykernel_3419/2310005255.py:2: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  activity_labels = pd.read_csv(

In [34]:

y_test_named.head()

0    STANDING
1    STANDING
2    STANDING
3    STANDING
4    STANDING
Name: 0, dtype: object

## Files:
####  total_acc_x_train.txt, total_acc_y_train.txt, total_acc_z_train.txt

#**Meaning**:
 These are the raw accelerometer signals (body acceleration + gravity).

Axes: Same as above (x, y, z).

Use: Useful for recognizing postures (sitting, standing, lying) because gravity dominates when the body is still.