<a href="https://colab.research.google.com/github/BishalDas1010/BIT_project_TInyML/blob/main/PAMAP2_Physical_Activity_Monitoring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
path ="/content/drive/MyDrive/Dataset_For_Bit/pamap2+physical+activity+monitoring.zip"

In [2]:
import zipfile



with zipfile.ZipFile(path, "r") as zip_ref:
    zip_ref.extractall("extracted_files")

print("ZIP extracted successfully!")

ZIP extracted successfully!

In [3]:
import zipfile

pathh ="/content/extracted_files/PAMAP2_Dataset.zip"

with zipfile.ZipFile(pathh, "r") as zip_ref:
    zip_ref.extractall("extracted_files")

print("ZIP extracted successfully!")

ZIP extracted successfully!

In [4]:
import pandas as pd
df = pd.read_csv("/content/extracted_files/PAMAP2_Dataset/Protocol/subject102.dat", sep=' ', header=None)

In [5]:
lis = [
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject101.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject105.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject106.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject108.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject109.dat",
]

In [6]:
lis[1]
df =["df1","df2","df3","df4","df5"]
df_list =[]

In [7]:
for  i in range(len(lis)):
  df[i] = pd.read_csv(lis[i], sep=' ', header=None)
  df[i].head()
  print(f"${list[i]}")
  print(df[i].shape)
  print(df[i].head())
  df_list.append(df[i])

$list[0]
(376417, 54)
     0   1      2     3        4        5        6        7        8   \
0  8.38   0  104.0  30.0  2.37223  8.60074  3.51048  2.43954  8.76165
1  8.39   0    NaN  30.0  2.18837  8.56560  3.66179  2.39494  8.55081
2  8.40   0    NaN  30.0  2.37357  8.60107  3.54898  2.30514  8.53644
3  8.41   0    NaN  30.0  2.07473  8.52853  3.66021  2.33528  8.53622
4  8.42   0    NaN  30.0  2.22936  8.83122  3.70000  2.23055  8.59741

        9   ...        44        45        46       47       48       49   50  \
0  3.35465  ...  0.008300  0.009250 -0.017580 -61.1888 -38.9599 -58.1438  1.0
1  3.64207  ... -0.006577 -0.004638  0.000368 -59.8479 -38.8919 -58.5253  1.0
2  3.73280  ...  0.003014  0.000148  0.022495 -60.7361 -39.4138 -58.3999  1.0
3  3.73277  ...  0.003175 -0.020301  0.011275 -60.4091 -38.7635 -58.3956  1.0
4  3.76295  ...  0.012698 -0.014303 -0.002823 -61.5199 -39.3879 -58.2694  1.0

    51   52   53
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  0.0  0.0
4  0.0  0.0  0.0

[5 rows x 54 columns]
$list[1]
(374783, 54)
     0   1   2     3        4        5        6        7        8        9   \
0  5.70   0 NaN  34.0  2.22755  9.65418  2.38862  2.31968  9.60752  2.58278
1  5.71   0 NaN  34.0  2.37550  9.57647  2.31412  2.45657  9.62177  2.71852
2  5.72   0 NaN  34.0  2.94208  9.53415  2.32275  2.78876  9.64961  2.76342
3  5.73   0 NaN  34.0  3.47541  9.75837  2.40696  3.33080  9.66073  2.68734
4  5.74   0 NaN  34.0  3.54617  9.83232  2.25382  3.67642  9.71848  2.50565

   ...        44        45        46       47       48       49        50  \
0  ... -0.017907  0.009340  0.050097 -32.7091  31.4772  44.2318  0.255373
1  ... -0.070091  0.002312  0.053832 -33.0782  30.9814  44.5148  0.251163
2  ... -0.084468  0.034249  0.030462 -32.5619  30.6982  44.5169  0.250643
3  ... -0.030789  0.058615  0.055252 -32.8212  30.9690  44.6575  0.250917
4  ... -0.020063  0.020903  0.059653 -33.1869  30.0856  44.5154  0.249631

         51        52        53
0  0.783075  0.084602  0.560732
1  0.785583  0.076319  0.560314
2  0.786419  0.072038  0.559941
3  0.786967  0.071013  0.559179
4  0.786602  0.066861  0.560777

[5 rows x 54 columns]
$list[2]
(361817, 54)
     0   1   2        3        4        5        6        7        8   \
0  5.89   0 NaN  32.6875 -6.39979  2.58932  6.67079 -6.26368  2.57551
1  5.90   0 NaN  32.6875 -6.40246  2.39929  6.63290 -6.20403  2.54483
2  5.91   0 NaN  32.6875 -6.47751  2.47575  6.63152 -6.23328  2.60549
3  5.92   0 NaN  32.6875 -6.32742  2.70155  6.55603 -6.24898  2.62062
4  5.93   0 NaN  32.6875 -6.43250  2.55301  6.82437 -6.23341  2.60548

        9   ...        44        45        46       47       48       49  \
0  6.98619  ...  0.067704  0.001500 -0.011983 -33.6479  27.0146  43.0990
1  6.94089  ...  0.030155  0.025643 -0.007916 -33.7877  27.1478  42.2474
2  6.98609  ...  0.067642 -0.028377  0.004280 -34.8053  27.0702  42.3857
3  6.89547  ...  0.018724  0.012499  0.014775 -33.9116  26.8960  42.1054
4  6.97099  ... -0.009428 -0.012789 -0.010744 -34.0416  27.1609  42.3883

         50        51        52        53
0  0.220967  0.773766  0.285557  0.520497
1  0.221332  0.773236  0.286219  0.520765
2  0.221819  0.773033  0.286287  0.520822
3  0.221836  0.772801  0.287420  0.520535
4  0.221799  0.772786  0.288440  0.520008

[5 rows x 54 columns]
$list[3]
(408031, 54)
     0   1   2        3        4        5         6        7        8   \
0  5.89   0 NaN  33.3125 -9.79760 -1.45670  1.014380 -9.70702 -1.60337
1  5.90   0 NaN  33.3125 -9.91204 -1.41822  0.974050 -9.78262 -1.60285
2  5.91   0 NaN  33.3125 -9.87531 -1.57027  0.975113 -9.78237 -1.57265
3  5.92   0 NaN  33.3125 -9.72175 -1.60870  1.054520 -9.70677 -1.60334
4  5.93   0 NaN  33.3125 -9.79920 -1.49497  0.975999 -9.58657 -1.57408

        9   ...        44        45        46       47       48       49  \
0  1.32098  ... -0.013731  0.010364  0.010731 -35.4550  38.3829 -17.9083
1  1.29085  ...  0.004436 -0.005926 -0.006704 -35.4508  38.2543 -17.7663
2  1.29079  ...  0.022508 -0.002265  0.014646 -35.6984  38.2688 -17.0580
3  1.35118  ... -0.006964  0.035314  0.010982 -34.9492  38.7447 -17.6233
4  1.27549  ... -0.015835 -0.001065 -0.000410 -35.2105  38.8857 -17.9080

         50        51        52        53
0  0.546211  0.370903  0.695334  0.283892
1  0.545806  0.370867  0.695680  0.283872
2  0.545484  0.371607  0.695437  0.284117
3  0.545474  0.372077  0.694859  0.284935
4  0.545810  0.372349  0.694122  0.285732

[5 rows x 54 columns]
$list[4]
(8477, 54)
      0   1      2      3         4        5        6         7        8   \
0  15.47   0  141.0  24.75  -9.98278  2.61759  2.46038 -10.23410  2.69055
1  15.48   0    NaN  24.75  -9.75577  2.46441  2.50279  -9.96280  2.56789
2  15.49   0    NaN  24.75 -10.32720  2.43953  3.45650  -9.96105  2.44737
3  15.50   0    NaN  24.75 -10.99920  2.29537  3.71633 -10.53000  2.45190
4  15.51   0    NaN  24.75 -10.88630  1.83990  3.79653 -11.07110  2.25982

        9   ...        44        45        46       47       48       49  \
0  2.45977  ...  0.714237 -0.235885 -0.341782 -44.2263 -10.2857  7.36341
1  2.58057  ...  0.238571 -0.279597 -0.536439 -44.3354 -10.7931  8.07278
2  2.91305  ... -0.122434 -0.307176 -0.737734 -44.4643 -10.6575  8.21400
3  3.36664  ... -0.347597 -0.349365 -0.938808 -44.2026 -11.1868  7.79004
4  3.73003  ... -0.469862 -0.457702 -1.059880 -43.4225 -11.8694  7.79357

         50        51        52        53
0  0.466904 -0.486197  0.608846 -0.418234
1  0.466590 -0.488971  0.607694 -0.417024
2  0.466964 -0.492189  0.607102 -0.413669
3  0.468730 -0.494896  0.606311 -0.409581
4  0.469978 -0.497652  0.605975 -0.405287

[5 rows x 54 columns]

In [8]:
#datasetcreate
columns = [
    'timestamp',
    'activityID',
    'heartRate',

    # Hand IMU
    'hand_temperature',
    'hand_acc16_x',
    'hand_acc16_y',
    'hand_acc16_z',
    'hand_acc6_x',
    'hand_acc6_y',
    'hand_acc6_z',
    'hand_gyro_x',
    'hand_gyro_y',
    'hand_gyro_z',
    'hand_mag_x',
    'hand_mag_y',
    'hand_mag_z',
    'hand_orient_1',
    'hand_orient_2',
    'hand_orient_3',
    'hand_orient_4',

    # Chest IMU
    'chest_temperature',
    'chest_acc16_x',
    'chest_acc16_y',
    'chest_acc16_z',
    'chest_acc6_x',
    'chest_acc6_y',
    'chest_acc6_z',
    'chest_gyro_x',
    'chest_gyro_y',
    'chest_gyro_z',
    'chest_mag_x',
    'chest_mag_y',
    'chest_mag_z',
    'chest_orient_1',
    'chest_orient_2',
    'chest_orient_3',
    'chest_orient_4',

    # Ankle IMU
    'ankle_temperature',
    'ankle_acc16_x',
    'ankle_acc16_y',
    'ankle_acc16_z',
    'ankle_acc6_x',
    'ankle_acc6_y',
    'ankle_acc6_z',
    'ankle_gyro_x',
    'ankle_gyro_y',
    'ankle_gyro_z',
    'ankle_mag_x',
    'ankle_mag_y',
    'ankle_mag_z',
    'ankle_orient_1',
    'ankle_orient_2',
    'ankle_orient_3',
    'ankle_orient_4'
]
len(columns)

54

In [9]:
path=[
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject101.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject102.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject103.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject104.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject105.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject106.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject107.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject108.dat",
    "/content/extracted_files/PAMAP2_Dataset/Protocol/subject109.dat"
]

In [10]:
df_list =[]

timestamp
activityID
heartRate
hand IMU data
chest IMU data
ankle IMU data

In [11]:
import pandas as pd

dataframes = []


for i in range(0,len(path)-1):
    df = pd.read_csv(
        path[i],
        sep=r"\s+",
        header=None,
        names=columns
    )
    dataframes.append(df)
    print(f"Loaded {path[i]}, shape: {df.shape}")


df1 = dataframes[0]
df2 = dataframes[1]
df3 = dataframes[2]
df4 = dataframes[3]
df5 = dataframes[4]
df6 = dataframes[5]
df7 = dataframes[6]
df8 = dataframes[7]
combine_df_y = pd.concat([df1['activityID'], df2['activityID'],df3['activityID'],df4['activityID'],df5['activityID'],df6['activityID'],df7['activityID'],df8['activityID']], ignore_index=True)

print(df1.head())
print(df1.shape)

Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject101.dat, shape: (376417, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject102.dat, shape: (447000, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject103.dat, shape: (252833, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject104.dat, shape: (329576, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject105.dat, shape: (374783, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject106.dat, shape: (361817, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject107.dat, shape: (313599, 54)
Loaded /content/extracted_files/PAMAP2_Dataset/Protocol/subject108.dat, shape: (408031, 54)
   timestamp  activityID  heartRate  hand_temperature  hand_acc16_x  \
0       8.38           0      104.0              30.0       2.37223
1       8.39           0        NaN              30.0       2.18837
2       8.40           0        NaN              30.0       2.37357
3       8.41           0        NaN              30.0       2.07473
4       8.42           0        NaN              30.0       2.22936

   hand_acc16_y  hand_acc16_z  hand_acc6_x  hand_acc6_y  hand_acc6_z  ...  \
0       8.60074       3.51048      2.43954      8.76165      3.35465  ...
1       8.56560       3.66179      2.39494      8.55081      3.64207  ...
2       8.60107       3.54898      2.30514      8.53644      3.73280  ...
3       8.52853       3.66021      2.33528      8.53622      3.73277  ...
4       8.83122       3.70000      2.23055      8.59741      3.76295  ...

   ankle_gyro_x  ankle_gyro_y  ankle_gyro_z  ankle_mag_x  ankle_mag_y  \
0      0.008300      0.009250     -0.017580     -61.1888     -38.9599
1     -0.006577     -0.004638      0.000368     -59.8479     -38.8919
2      0.003014      0.000148      0.022495     -60.7361     -39.4138
3      0.003175     -0.020301      0.011275     -60.4091     -38.7635
4      0.012698     -0.014303     -0.002823     -61.5199     -39.3879

   ankle_mag_z  ankle_orient_1  ankle_orient_2  ankle_orient_3  ankle_orient_4
0     -58.1438             1.0             0.0             0.0             0.0
1     -58.5253             1.0             0.0             0.0             0.0
2     -58.3999             1.0             0.0             0.0             0.0
3     -58.3956             1.0             0.0             0.0             0.0
4     -58.2694             1.0             0.0             0.0             0.0

[5 rows x 54 columns]
(376417, 54)

In [12]:
df1['activityID'].value_counts()

activityID
0     126460
1      27187
6      23575
17     23573
2      23480
16     22941
4      22253
3      21717
5      21265
7      20265
12     15890
13     14899
24     12912
Name: count, dtype: int64

In [13]:
feature = [
"hand_acc16_x",
"hand_acc16_y",
"hand_acc16_z",
"hand_gyro_x",
"hand_gyro_y",
"hand_gyro_z"
]

In [14]:
X =df[feature]

In [15]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 408031 entries, 0 to 408030
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   hand_acc16_x  405880 non-null  float64
 1   hand_acc16_y  405880 non-null  float64
 2   hand_acc16_z  405880 non-null  float64
 3   hand_gyro_x   405880 non-null  float64
 4   hand_gyro_y   405880 non-null  float64
 5   hand_gyro_z   405880 non-null  float64
dtypes: float64(6)
memory usage: 18.7 MB

In [16]:
X.describe()

,hand_acc16_x,hand_acc16_y,hand_acc16_z,hand_gyro_x,hand_gyro_y,hand_gyro_z
count,405880.000000,405880.000000,405880.000000,405880.000000,405880.000000,405880.000000
mean,-5.384200,-4.169108,3.082906,-0.062992,0.059203,-0.033711
std,6.270890,5.924233,3.445358,1.307926,0.908610,1.524781
min,-106.527000,-104.301000,-55.963700,-20.965600,-13.390400,-15.218500
25%,-9.421582,-6.816100,0.867816,-0.314481,-0.167236,-0.268129
50%,-6.244030,-2.863665,2.591190,-0.010368,0.003951,-0.006765
75%,-1.510340,-1.295555,6.141882,0.259672,0.206406,0.246119
max,46.741800,62.033900,116.977000,19.601400,10.432100,14.309000

In [17]:
combine_df_x = combined_df = pd.concat([df1[feature], df2[feature],df3[feature],df4[feature]], ignore_index=True)

In [18]:
combine_df_x.head()

,hand_acc16_x,hand_acc16_y,hand_acc16_z,hand_gyro_x,hand_gyro_y,hand_gyro_z
0,2.37223,8.60074,3.51048,-0.092217,0.056812,-0.015845
1,2.18837,8.56560,3.66179,-0.024413,0.047759,0.006474
2,2.37357,8.60107,3.54898,-0.057976,0.032574,-0.006988
3,2.07473,8.52853,3.66021,-0.002352,0.032810,-0.003747
4,2.22936,8.83122,3.70000,0.012269,0.018305,-0.053325

In [19]:
combine_df_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1405826 entries, 0 to 1405825
Data columns (total 6 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   hand_acc16_x  1398907 non-null  float64
 1   hand_acc16_y  1398907 non-null  float64
 2   hand_acc16_z  1398907 non-null  float64
 3   hand_gyro_x   1398907 non-null  float64
 4   hand_gyro_y   1398907 non-null  float64
 5   hand_gyro_z   1398907 non-null  float64
dtypes: float64(6)
memory usage: 64.4 MB

In [20]:
combine_df_x.head()

,hand_acc16_x,hand_acc16_y,hand_acc16_z,hand_gyro_x,hand_gyro_y,hand_gyro_z
0,2.37223,8.60074,3.51048,-0.092217,0.056812,-0.015845
1,2.18837,8.56560,3.66179,-0.024413,0.047759,0.006474
2,2.37357,8.60107,3.54898,-0.057976,0.032574,-0.006988
3,2.07473,8.52853,3.66021,-0.002352,0.032810,-0.003747
4,2.22936,8.83122,3.70000,0.012269,0.018305,-0.053325

In [21]:
combine_df_x.describe()

,hand_acc16_x,hand_acc16_y,hand_acc16_z,hand_gyro_x,hand_gyro_y,hand_gyro_z
count,1.398907e+06,1.398907e+06,1.398907e+06,1.398907e+06,1.398907e+06,1.398907e+06
mean,-4.769426e+00,4.892550e+00,3.045617e+00,1.071207e-02,2.546459e-02,-1.027477e-02
std,5.875211e+00,4.216369e+00,3.849335e+00,1.343674e+00,9.055717e-01,1.479819e+00
min,-1.276490e+02,-8.123440e+01,-4.643560e+01,-2.198240e+01,-2.221270e+01,-1.669970e+01
25%,-8.918550e+00,2.534330e+00,9.464640e-01,-3.428740e-01,-2.063870e-01,-2.967750e-01
50%,-5.575380e+00,4.575040e+00,2.994390e+00,-4.198580e-03,7.342450e-03,-5.227380e-03
75%,-6.875805e-01,7.099350e+00,5.842385e+00,3.294555e-01,2.465655e-01,2.726940e-01
max,6.285960e+01,1.068980e+02,1.322950e+02,2.625910e+01,1.698350e+01,1.179370e+01

In [23]:
combine_df_x.shape

(1405826, 6)

In [24]:
combine_df_x.describe()

,hand_acc16_x,hand_acc16_y,hand_acc16_z,hand_gyro_x,hand_gyro_y,hand_gyro_z
count,1.398907e+06,1.398907e+06,1.398907e+06,1.398907e+06,1.398907e+06,1.398907e+06
mean,-4.769426e+00,4.892550e+00,3.045617e+00,1.071207e-02,2.546459e-02,-1.027477e-02
std,5.875211e+00,4.216369e+00,3.849335e+00,1.343674e+00,9.055717e-01,1.479819e+00
min,-1.276490e+02,-8.123440e+01,-4.643560e+01,-2.198240e+01,-2.221270e+01,-1.669970e+01
25%,-8.918550e+00,2.534330e+00,9.464640e-01,-3.428740e-01,-2.063870e-01,-2.967750e-01
50%,-5.575380e+00,4.575040e+00,2.994390e+00,-4.198580e-03,7.342450e-03,-5.227380e-03
75%,-6.875805e-01,7.099350e+00,5.842385e+00,3.294555e-01,2.465655e-01,2.726940e-01
max,6.285960e+01,1.068980e+02,1.322950e+02,2.625910e+01,1.698350e+01,1.179370e+01

Y

In [25]:
target = 'activityID'

In [26]:
Y =combine_df_y

In [27]:
Y.unique()
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: activityID, dtype: int64

In [28]:
Y =Y[ Y !=0]

In [29]:
Y.unique()

array([ 1,  2,  3, 17, 16, 12, 13,  4,  7,  6,  5, 24])

tacking help from ai
PAMAP2
↓
Select 6 features
↓
Combine subjects
↓
Remove activityID = 0
↓
Normalize
↓
Create windows (100,6)
↓
Train TinyCNN

In [30]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# The variables combine_df_x and Y must have the same indices for alignment
# Combine them temporarily to drop NaNs across both
combined_temp = pd.concat([combine_df_x, Y], axis=1).dropna()

# Separate back into X and Y
X_clean = combined_temp[feature].values
Y_clean = combined_temp['activityID']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_clean)

print(f"Cleaned data shape: {X_scaled.shape}")

Cleaned data shape: (912614, 6)

In [31]:
X.shape

(408031, 6)

In [32]:
Y.shape

(1936481,)

In [33]:
window_size = 100

In [34]:
X_windows = []
y_windows = []

window_size = 100
# Use X_scaled which was cleaned in wvh1CWx_kPym
limit = len(X_scaled)

for i in range(0, limit - window_size, window_size):
    X_windows.append(X_scaled[i:i+window_size])
    y_windows.append(Y_clean.iloc[i+window_size-1])

X_windows = np.array(X_windows, dtype='float32')
y_windows = np.array(y_windows)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_windows, y_windows, test_size=0.2, random_state=42)

print("Data prepared. X_train shape:", X_train.shape)

Data prepared. X_train shape: (7300, 100, 6)

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_windows,
    y_windows,
    test_size=0.2,
    random_state=42
)

In [36]:
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Input

le = LabelEncoder()
y_train_mapped = le.fit_transform(y_train)
y_test_mapped = le.transform(y_test)

# Re-define model to ensure weight reset
model = Sequential([
    Input(shape=(100, 6)),
    Conv1D(filters=16, kernel_size=3, activation='relu'),
    MaxPooling1D(2),
    Conv1D(filters=32, kernel_size=3, activation='relu'),
    MaxPooling1D(2),
    Flatten(),
    Dense(32, activation='relu'),
    Dense(len(le.classes_), activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

history = model.fit(
    X_train,
    y_train_mapped,
    epochs=15,
    batch_size=64,
    validation_data=(X_test, y_test_mapped)
)
model.summary()

# Save the model after training
model.save("har_model.h5")

Epoch 1/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.4525 - loss: 1.7367 - val_accuracy: 0.6818 - val_loss: 1.1673
Epoch 2/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.7337 - loss: 0.9667 - val_accuracy: 0.7464 - val_loss: 0.9147
Epoch 3/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7652 - loss: 0.8132 - val_accuracy: 0.7716 - val_loss: 0.8340
Epoch 4/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7945 - loss: 0.7258 - val_accuracy: 0.7755 - val_loss: 0.7943
Epoch 5/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8052 - loss: 0.6695 - val_accuracy: 0.7782 - val_loss: 0.7719
Epoch 6/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8112 - loss: 0.6339 - val_accuracy: 0.7831 - val_loss: 0.7725
Epoch 7/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8249 - loss: 0.5962 - val_accuracy: 0.7946 - val_loss: 0.7448
Epoch 8/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8353 - loss: 0.5699 - val_accuracy: 0.7974 - val_loss: 0.7191
Epoch 9/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8400 - loss: 0.5462 - val_accuracy: 0.8034 - val_loss: 0.7289
Epoch 10/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8405 - loss: 0.5272 - val_accuracy: 0.7963 - val_loss: 0.7156
Epoch 11/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8526 - loss: 0.5056 - val_accuracy: 0.7979 - val_loss: 0.7092
Epoch 12/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8589 - loss: 0.4836 - val_accuracy: 0.8160 - val_loss: 0.7136
Epoch 13/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8649 - loss: 0.4662 - val_accuracy: 0.8012 - val_loss: 0.7138
Epoch 14/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8682 - loss: 0.4565 - val_accuracy: 0.8149 - val_loss: 0.6956
Epoch 15/15
115/115 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8727 - loss: 0.4401 - val_accuracy: 0.8122 - val_loss: 0.7142

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d (Conv1D)                 │ (None, 98, 16)         │           304 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d (MaxPooling1D)    │ (None, 49, 16)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1d_1 (Conv1D)               │ (None, 47, 32)         │         1,568 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 23, 32)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 736)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │        23,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 12)             │           396 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 77,558 (302.96 KB)

 Trainable params: 25,852 (100.98 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 51,706 (201.98 KB)

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [37]:
# Use the mapped labels for evaluation to match the model's output layer
loss, acc = model.evaluate(X_test.astype('float32'), y_test_mapped)

print("Accuracy:", acc)

58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8122 - loss: 0.7142
Accuracy: 0.8121577501296997

In [38]:
sample = X_test[2]

print(sample.shape)

(100, 6)

In [39]:
sample = np.expand_dims(sample, axis=0)

print(sample.shape)

(1, 100, 6)

In [40]:
pred = model.predict(sample)

predicted_class = np.argmax(pred)

predicted_activity = le.inverse_transform([predicted_class])

print("Predicted:", predicted_activity[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
Predicted: 3.0

In [41]:
sample.shape

(1, 100, 6)

In [42]:
for i in range(5):
    sample = np.expand_dims(X_test[i], axis=0)

    pred = model.predict(sample, verbose=0)

    pred_class = np.argmax(pred)

    predicted = le.inverse_transform([pred_class])[0]

    actual = y_test[i]

    print(f"Sample {i}")
    print("Actual    :", actual)
    print("Predicted :", predicted)
    print()

print()

Sample 0
Actual    : 3.0
Predicted : 3.0

Sample 1
Actual    : 16.0
Predicted : 16.0

Sample 2
Actual    : 3.0
Predicted : 3.0

Sample 3
Actual    : 17.0
Predicted : 17.0

Sample 4
Actual    : 4.0
Predicted : 4.0

In [43]:
from tensorflow.keras.models import load_model
import numpy as np

model = load_model("har_model.h5")

# Assuming 'sample' is a window of data for prediction, as defined in previous cells
prediction = model.predict(sample)
print(np.argmax(prediction))

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step
3